USE [master]
GO
/****** Object:  Database [LaboratorioBD]    Script Date: 17/02/2020 11:09:31 p. m. ******/
CREATE DATABASE [LaboratorioBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LaboratorioBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LaboratorioBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LaboratorioBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LaboratorioBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [LaboratorioBD] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LaboratorioBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LaboratorioBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LaboratorioBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LaboratorioBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LaboratorioBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LaboratorioBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [LaboratorioBD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LaboratorioBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LaboratorioBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LaboratorioBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LaboratorioBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LaboratorioBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LaboratorioBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LaboratorioBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LaboratorioBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LaboratorioBD] SET  ENABLE_BROKER 
GO
ALTER DATABASE [LaboratorioBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LaboratorioBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LaboratorioBD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LaboratorioBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LaboratorioBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LaboratorioBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LaboratorioBD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LaboratorioBD] SET RECOVERY FULL 
GO
ALTER DATABASE [LaboratorioBD] SET  MULTI_USER 
GO
ALTER DATABASE [LaboratorioBD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LaboratorioBD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LaboratorioBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LaboratorioBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LaboratorioBD] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'LaboratorioBD', N'ON'
GO
ALTER DATABASE [LaboratorioBD] SET QUERY_STORE = OFF
GO
ALTER DATABASE [LaboratorioBD] SET  READ_WRITE 
GO
