USE [master]
GO
/****** Object:  Database [Ejemplo2]    Script Date: 12/02/2020 10:36:03 a. m. ******/
CREATE DATABASE [Ejemplo2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ejemplo2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Ejemplo2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ejemplo2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Ejemplo2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Ejemplo2] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ejemplo2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ejemplo2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ejemplo2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ejemplo2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ejemplo2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ejemplo2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ejemplo2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ejemplo2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ejemplo2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ejemplo2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ejemplo2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ejemplo2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ejemplo2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ejemplo2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ejemplo2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ejemplo2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Ejemplo2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ejemplo2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ejemplo2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ejemplo2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ejemplo2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ejemplo2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ejemplo2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ejemplo2] SET RECOVERY FULL 
GO
ALTER DATABASE [Ejemplo2] SET  MULTI_USER 
GO
ALTER DATABASE [Ejemplo2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ejemplo2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ejemplo2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ejemplo2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ejemplo2] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Ejemplo2', N'ON'
GO
ALTER DATABASE [Ejemplo2] SET QUERY_STORE = OFF
GO
ALTER DATABASE [Ejemplo2] SET  READ_WRITE 
GO
